export type AgentType =
    | "startup"
    | "market"
    | "competitor"
    | "investor"
    | "innovation"
    | "customerPersona"
    | "pricing"
    | "businessModel"
    | "financial"
    | "swot"
    | "risk"
    | "gtm"
    | "technical"
    | "marketing"
    | "regulatory";
